export const uselessSites = [
  { name: 'Mystic Square', url: 'https://sliding.toys/mystic-square/8-puzzle/daily/' },
  { name: 'Long Doge Challenge', url: 'https://longdogechallenge.com/' },
  { name: 'Mini Maze', url: 'https://maze.toys/mazes/mini/daily/' },
  { name: 'Optical Toys', url: 'https://optical.toys' },
  { name: 'Zen Garden', url: 'https://paint.toys/zen-garden/' },
  { name: 'Pug in a Rug', url: 'https://puginarug.com' },
  { name: 'Classic Memory', url: 'https://memory.toys/classic/easy/' },
  { name: 'Judge a Book', url: 'https://alwaysjudgeabookbyitscover.com' },
  { name: 'Peg Solitaire', url: 'https://clicking.toys/peg-solitaire/english/' },
  { name: 'Weird or Confusing', url: 'https://weirdorconfusing.com/' },
  { name: 'Checkbox Scale', url: 'https://checkbox.toys/scale/' },
  { name: 'Mondrian and Me', url: 'https://mondrianandme.com/' },
  { name: 'Cruel Maze', url: 'https://cruel.toys/maze' },
  { name: 'One Square Minesweeper', url: 'https://onesquareminesweeper.com/' },
  { name: 'Cursor Effects', url: 'https://cursoreffects.com' },
  { name: 'Patience Toys', url: 'https://patience.toys' },
  { name: 'Floating QR Code', url: 'https://floatingqrcode.com/' },
  { name: 'That Finger', url: 'https://thatsthefinger.com/' },
  { name: 'Cant Not Tweet This', url: 'https://cant-not-tweet-this.com/' },
  { name: 'Heeeeeeeey', url: 'https://heeeeeeeey.com/' },
  { name: 'Sand Paint', url: 'https://paint.toys/sand/' },
  { name: 'Ant Toys', url: 'https://ant.toys' },
  { name: 'Snapegiator', url: 'https://musical.toys/toys/snapegiator/' },
  { name: 'The Vintage Web', url: 'https://thevintageweb.com/' },
  { name: 'Toms Toys', url: 'https://toms.toys' },
  { name: 'Bury Me With My Money', url: 'https://burymewithmymoney.com/' },
  { name: 'Smash The Walls', url: 'https://smashthewalls.com/' },
  { name: 'Jackson Pollock', url: 'https://jacksonpollock.org/' },
  { name: 'Duck Street', url: 'https://duckstreet.net/' },
  { name: 'Drawing Garden', url: 'https://drawing.garden/' },
  { name: 'Try Pap', url: 'https://www.trypap.com/' },
  { name: 'Symmetry Paint', url: 'https://paint.toys/symmetry/' },
  { name: 'Unicode Joy', url: 'https://xn--gi8h42h.ws/' },
  { name: 'Move Now Think Later', url: 'https://www.movenowthinklater.com/' },
  { name: '15 Puzzle', url: 'https://sliding.toys/mystic-square/15-puzzle/daily/' },
  { name: 'Checkbox Race', url: 'https://checkboxrace.com/' },
  { name: 'RGB', url: 'https://www.rrrgggbbb.com/' },
  { name: 'Koalas to the Max', url: 'https://www.koalastothemax.com/' },
  { name: 'Rotating Sandwiches', url: 'https://rotatingsandwiches.com/' },
  { name: 'Everyday Im', url: 'http://www.everydayim.com/' },
  { name: 'Random Colour', url: 'https://randomcolour.com/' },
  { name: 'Man in the Dark', url: 'https://maninthedark.com/' },
  { name: 'Cat Bounce', url: 'https://cat-bounce.com/' },
  { name: 'Paint Toys', url: 'https://paint.toys/' },
  { name: 'Chris McKenzie', url: 'https://chrismckenzie.com/' },
  { name: 'The Zen Zone', url: 'https://thezen.zone/' },
  { name: 'I Has a Bucket', url: 'https://ihasabucket.com/' },
  { name: 'Corndog on Corndog', url: 'https://corndogoncorndog.com/' },
  { name: 'Hacker Typer', url: 'https://hackertyper.com/' },
  { name: 'Pointer Pointer', url: 'https://pointerpointer.com' },
  { name: 'I Am Ninja', url: 'https://imaninja.com/' },
  { name: 'Calligram Paint', url: 'https://paint.toys/calligram/' },
  { name: 'Nulling the Void', url: 'https://nullingthevoid.com/' },
  { name: 'Much Better Than This', url: 'https://www.muchbetterthanthis.com/' },
  { name: 'Yes No If', url: 'https://www.yesnoif.com/' },
  { name: 'Lacquer Lacquer', url: 'https://lacquerlacquer.com' },
  { name: 'Flip Grid', url: 'https://clicking.toys/flip-grid/neat-nine/3-holes/' },
  { name: 'Potato or Tomato', url: 'https://potatoortomato.com/' },
  { name: 'I Am Awesome', url: 'https://iamawesome.com/' },
  { name: 'Strobe Cool', url: 'https://strobe.cool/' },
  { name: 'Not a Jump Scare', url: 'http://thisisnotajumpscare.com/' },
  { name: 'Polyrhythm', url: 'https://musical.toys/toys/polyrhythm/' },
  { name: 'Crouton', url: 'https://crouton.net/' },
  { name: 'Wut Dafuk', url: 'https://wutdafuk.com/' },
  { name: 'Unicode Snowman', url: 'https://unicodesnowmanforyou.com/' },
  { name: 'Shovel and Shoot', url: 'https://shovelandshoot.com/' },
  { name: 'Cross Divisions', url: 'https://www.crossdivisions.com/' },
  { name: 'Memory Maze', url: 'https://memory.toys/maze/easy/' },
  { name: 'Boring Boring Boring', url: 'https://boringboringboring.com/' },
  { name: 'Patience is a Virtue', url: 'http://www.patience-is-a-virtue.org/' },
  { name: 'Pixels Fighting', url: 'https://pixelsfighting.com/' },
  { name: 'Existential Crisis', url: 'https://existentialcrisis.com/' },
  { name: 'OMFG Dogs', url: 'https://www.omfgdogs.com/' },
  { name: 'Oct82', url: 'https://oct82.com/' },
  { name: 'Blank Windows', url: 'https://www.blankwindows.com/' },
  { name: 'Tunnel Snakes', url: 'http://tunnelsnakes.com/' },
  { name: 'Trash Loop', url: 'https://www.trashloop.com/' },
  { name: 'Wiggly Me', url: 'https://wigglyme.com/' },
  { name: 'Double Pressure', url: 'https://www.doublepressure.com/' },
  { name: 'Thatcher Effect', url: 'https://optical.toys/thatcher-effect/' },
  { name: 'Musical Toys', url: 'https://musical.toys' },
  { name: 'Not Day of the Week', url: 'https://notdayoftheweek.com/' },
  { name: 'Number Toys', url: 'https://number.toys/' },
  { name: 'Klondike', url: 'https://card.toys/klondike/' },
  { name: 'Great Big Nothing', url: 'https://greatbignothing.com/' },
  { name: 'Zoom Quilt', url: 'https://zoomquilt.org/' },
  { name: 'Cruel Hunt', url: 'https://cruel.toys/hunt' },
  { name: 'Troxler Fade', url: 'https://optical.toys/troxler-fade/' },
  { name: 'Dad Laugh Button', url: 'https://dadlaughbutton.com/' },
  { name: 'Remoji', url: 'https://remoji.com/' },
  { name: 'Pendulum Waves', url: 'https://musical.toys/toys/pendulum-waves/' },
  { name: 'Paper Toilet', url: 'https://papertoilet.com/' },
  { name: 'Looped for Infinity', url: 'https://loopedforinfinity.com/' },
  { name: 'Ripe for Debate', url: 'https://www.ripefordebate.com/' },
  { name: 'Bouncing DVD Logo', url: 'https://www.bouncingdvdlogo.com/' },
  { name: 'Toybox', url: 'https://toybox.toms.toys' },
  { name: 'Monkey Challenge', url: 'https://memory.toys/monkey-challenge/easy/' },
  { name: 'Memory Toys', url: 'https://memory.toys' },
  { name: 'Eel Slap', url: 'http://eelslap.com/' },
  { name: 'Endless Horse', url: 'http://endless.horse/' },
  { name: 'Corndog', url: 'http://corndog.io/' },
  { name: 'Republic of Mangoes', url: 'http://www.republiquedesmangues.fr/' },
  { name: 'Staggering Beauty', url: 'http://www.staggeringbeauty.com/' },
  { name: 'Ninja Flex', url: 'http://ninjaflex.com/' },
  { name: 'Is My Computer On', url: 'http://www.ismycomputeron.com/' },
  { name: 'Doughnut Kitten', url: 'https://doughnutkitten.com/' },
  { name: 'Chillest Monkey', url: 'http://chillestmonkey.com/' },
  { name: 'Scroll O Meter', url: 'http://scroll-o-meter.club/' },
  { name: 'Ten Cents', url: 'http://tencents.info/' },
  { name: 'Chihuahua Spin', url: 'http://chihuahuaspin.com/' },
  { name: 'Greedy Pig', url: 'https://dice.toys/toy/greedy-pig/' },
  { name: 'Yeah Lemons', url: 'http://yeahlemons.com/' },
  { name: 'Wowen Wilson Quiz', url: 'http://wowenwilsonquiz.com' },
  { name: 'Build Shruggie', url: 'http://buildshruggie.com/' },
  { name: 'River of Reverence', url: 'https://poetic.toys/poems/river-of-reverence/' },
]
